variable "aks_cluster_rg_name" {}
variable "aks_location" {}
variable "aks_cluster_name" {}
variable "aks_node_count" {}
variable "aks_node_type" {}
variable "aks_svc_principal_client_id" {}
variable "aks_svc_principal_client_secret" {}
variable "aks_dns_prefix" {}
variable "aks_kubernetes_version" {}
variable "aks_node_os_disk_gb" {}
