aks_cluster_rg_name             = "cicd-cluster001"
aks_location                    = "westeurope"
aks_cluster_name                = "cicd-cluster001"
aks_node_count                  = "1"
aks_node_type                   = "Standard_B2s"
aks_svc_principal_client_id     = "cba59eda-4964-43d7-96fa-216dcaff1cb6"
aks_svc_principal_client_secret = "1db3eacd-c597-4aeb-acb0-3ec104f355c4"
aks_dns_prefix                  = "cicd-cluster001"
