apiVersion: v1
kind: Pod
metadata:
  name: tmp
spec:
  initContainers:
  - command:
      - '/bin/sh'
      - '-c'
      - 'unzip /tmp/ansible/ansible.zip -d /root/project'
    image: ksandermann/multistage-builder:2019-09-17
    imagePullPolicy: Always
    name: unzip
    resources: {}
    volumeMounts:
      - mountPath: /tmp/ansible/
        name: ansible-project
      - name: workdir
        mountPath: /root/project
  containers:
  - command:
    - '/bin/sh'
    - '-c'
    - 'ansible-playbook /root/project/ansible/playbooks/hello.yml'
    image: ksandermann/ansible:2.8.5
    imagePullPolicy: Always
    name: cloud-toolbox
    resources: {}
    volumeMounts:
      - mountPath: /tmp/ansible/
        name: ansible-project
      - name: workdir
        mountPath: /root/project
  volumes:
  - configMap:
      defaultMode: 420
      name: ansible-project
    name: ansible-project
  - name: workdir
    emptyDir: {}
